applicationSet:
  enabled: false

dex:
  enabled: false

notifications:
  enabled: false

controller:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

server:
  replicas: 1
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

redis:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi