services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    # volumes:
    #   - .:/app   # uncomment only for live-reload dev; omit for prod-like testing

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./app/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./app/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

volumes:
  grafana-data: